# ==========================================
# 1. THE PREFIX & MOUSE
# ==========================================
set -g prefix C-space
unbind C-b
bind C-space send-prefix

# Turn on mouse support (allows wheel scrolling and pane clicking)
set -g mouse on

# ==========================================
# 2. INTUITIVE SPLITS
# ==========================================
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# ==========================================
# 3. SMART VIM-TMUX NAVIGATION (No prefix required)
# ==========================================
# This script detects if the active pane is running Neovim/Vim.
# If YES: it sends the native Ctrl key to Vim.
# If NO: it uses tmux to switch terminal panes.
is_vim="echo '#{pane_current_command}' | grep -iqE '(^|\/)g?(view|l?n?vim?x?)(diff)?$'"


bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

# Use Vim keys when scrolling through history logs (Prefix + [)
setw -g mode-keys vi


# ==========================================
# STATUS BAR POSITION & STYLE
# ==========================================
# Move the status bar to the top of the terminal
set -g status-position top

# Set the background and foreground colors of the status bar
# (Using clean, dark minimalist slate tones as an example)
set -g status-style bg=#000000,fg=#ffffff

# Change the color of the active window tab in the list
set -g window-status-current-style bg=#ffffff,fg=#000000,bold

# Change the color of inactive window tabs
set -g window-status-style bg=#000000,fg=#ffffff

# Set pane border colors (The split line colors)
set -g pane-border-style fg=#380000
set -g pane-active-border-style fg=#ffffff

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -s escape-time 0
#setw -g aggressive-resize on  # fixes broken window resize. turn on when needed.
set -g allow-passthrough on


